spring:
  application:
    name: trade-engine

  datasource:
    url: jdbc:postgresql://localhost:5432/trade_engine
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      pool-name: TradingHikariPool
      max-lifetime: 1800000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false

app:
  exchanges:
    nobitex:
      name: NOBITEX
      base-url: https://apiv2.nobitex.ir
      token: 47fdebe4a10cfbf45de949c3690bb73f0346414b
    ramzinex:
      name: RAMZINEX
      base-url: https://api.ramzinex.com
      public-api: https://publicapi.ramzinex.com
      api-key: ApiKeySFlDbsC:802e0f3e6c3a4e51ad0aecb261928cbe2898fe66226128d1952064c2a39dfbd9
      private-token: b81d0cf60f082490d8610ce5ea2c7650

  http:
    timeout:
      connect: 2s
      read: 5s

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
